In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import matplotlib.pyplot as plt
import sklearn as skl
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(['EIN', 'NAME', 'ORGANIZATION', "SPECIAL_CONSIDERATIONS"], axis = 1)
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,STATUS,INCOME_AMT,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,1,0,5000,1
1,T3,Independent,C2000,Preservation,1,1-9999,108590,1
2,T5,CompanySponsored,C3000,ProductDev,1,0,5000,0
3,T3,CompanySponsored,C2000,Preservation,1,10000-24999,6692,1
4,T3,Independent,C1000,Heathcare,1,100000-499999,142590,1

In [3]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE      17
AFFILIATION            6
CLASSIFICATION        71
USE_CASE               5
STATUS                 2
INCOME_AMT             9
ASK_AMT             8747
IS_SUCCESSFUL          2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
application_df['APPLICATION_TYPE'].value_counts()

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = ['T25', 'T14', 'T29', 'T15', 'T17']

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
T9         156
T13         66
T12         27
T2          16
Other       11
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# You may find it helpful to look at CLASSIFICATION value counts >1
application_df[
    'CLASSIFICATION'
    ].value_counts()[
        application_df['CLASSIFICATION'].value_counts()<=10
        ].index

Index(['C1238', 'C1278', 'C1235', 'C1237', 'C7210', 'C2400', 'C1720', 'C4100',
       'C1257', 'C1600', 'C1260', 'C2710', 'C0', 'C3200', 'C1234', 'C1246',
       'C1267', 'C1256', 'C2190', 'C4200', 'C2600', 'C5200', 'C1370', 'C1248',
       'C6100', 'C1820', 'C1900', 'C1236', 'C3700', 'C2570', 'C1580', 'C1245',
       'C2500', 'C1570', 'C1283', 'C2380', 'C1732', 'C1728', 'C2170', 'C4120',
       'C8210', 'C2561', 'C4500', 'C2150'],
      dtype='object')

In [7]:

# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = [
    'C1238', 'C1278', 'C1235', 'C1237', 'C7210', 'C2400', 'C1720', 'C4100',
       'C1257', 'C1600', 'C1260', 'C2710', 'C0', 'C3200', 'C1234', 'C1246',
       'C1267', 'C1256', 'C2190', 'C4200', 'C2600', 'C5200', 'C1370', 'C1248',
       'C6100', 'C1820', 'C1900', 'C1236', 'C3700', 'C2570', 'C1580', 'C1245',
       'C2500', 'C1570', 'C1283', 'C2380', 'C1732', 'C1728', 'C2170', 'C4120',
       'C8210', 'C2561', 'C4500', 'C2150'
       ]

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df[
        'CLASSIFICATION'
        ].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df[
    'CLASSIFICATION'
    ].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
Other      118
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C2300       32
C7200       32
C1240       30
C8000       20
C7120       18
C1500       16
C6000       15
C1800       15
C1250       14
C8200       11
Name: CLASSIFICATION, dtype: int64

In [8]:
# Convert categorical data to numeric with `pd.get_dummies`
X = pd.get_dummies(application_df)

# Split our preprocessed data into our features and target arrays
y = application_df['IS_SUCCESSFUL']
X = X.drop(columns = "IS_SUCCESSFUL")
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    random_state=1, 
                                                    stratify=y)

In [9]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [16]:
len(list(X.columns))

63

In [34]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=75, activation="relu", input_dim=63))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=75, activation="relu"))

nn.add(tf.keras.layers.Dense(units=75, activation="relu"))
# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_23 (Dense)            (None, 75)                4800

 dense_24 (Dense)            (None, 75)                5700

 dense_25 (Dense)            (None, 75)                5700

 dense_26 (Dense)            (None, 1)                 76

=================================================================
Total params: 16,276
Trainable params: 16,276
Non-trainable params: 0
_________________________________________________________________

In [35]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [36]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=200)

Epoch 1/200
804/804 [==============================] - 3s 2ms/step - loss: 0.5759 - accuracy: 0.7196
Epoch 2/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5610 - accuracy: 0.7283
Epoch 3/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5580 - accuracy: 0.7298
Epoch 4/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5561 - accuracy: 0.7301
Epoch 5/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5554 - accuracy: 0.7299
Epoch 6/200
804/804 [==============================] - 2s 3ms/step - loss: 0.5544 - accuracy: 0.7305
Epoch 7/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5536 - accuracy: 0.7307
Epoch 8/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5536 - accuracy: 0.7308
Epoch 9/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5528 - accuracy: 0.7317
Epoch 10/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5522 - accuracy: 0.7317
Epoch 11/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5516 - accuracy: 0.7317
Epoch 12/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5519 - accuracy: 0.7311
Epoch 13/200
804/804 [==============================] - 2s 3ms/step - loss: 0.5509 - accuracy: 0.7323
Epoch 14/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5510 - accuracy: 0.7309
Epoch 15/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5503 - accuracy: 0.7320
Epoch 16/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5499 - accuracy: 0.7317
Epoch 17/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5489 - accuracy: 0.7323
Epoch 18/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5493 - accuracy: 0.7330
Epoch 19/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5489 - accuracy: 0.7329
Epoch 20/200
804/804 [==============================] - 2s 3ms/step - loss: 0.5488 - accuracy: 0.7338
Epoch 21/200
804/804 [==============================] - 2s 3ms/step - loss: 0.5487 - accuracy: 0.7339
Epoch 22/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5481 - accuracy: 0.7332
Epoch 23/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5479 - accuracy: 0.7333
Epoch 24/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5478 - accuracy: 0.7341
Epoch 25/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5475 - accuracy: 0.7344
Epoch 26/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5466 - accuracy: 0.7349
Epoch 27/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5470 - accuracy: 0.7334
Epoch 28/200
804/804 [==============================] - 2s 3ms/step - loss: 0.5467 - accuracy: 0.7334
Epoch 29/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5463 - accuracy: 0.7343
Epoch 30/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5466 - accuracy: 0.7341
Epoch 31/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5461 - accuracy: 0.7346
Epoch 32/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5460 - accuracy: 0.7340
Epoch 33/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5455 - accuracy: 0.7353
Epoch 34/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5454 - accuracy: 0.7338
Epoch 35/200
804/804 [==============================] - 2s 3ms/step - loss: 0.5452 - accuracy: 0.7353
Epoch 36/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5452 - accuracy: 0.7348
Epoch 37/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5453 - accuracy: 0.7344
Epoch 38/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5449 - accuracy: 0.7350
Epoch 39/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5452 - accuracy: 0.7349
Epoch 40/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5447 - accuracy: 0.7349
Epoch 41/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5448 - accuracy: 0.7350
Epoch 42/200
804/804 [==============================] - 2s 3ms/step - loss: 0.5444 - accuracy: 0.7349
Epoch 43/200
804/804 [==============================] - 2s 3ms/step - loss: 0.5443 - accuracy: 0.7349
Epoch 44/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5448 - accuracy: 0.7353
Epoch 45/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5444 - accuracy: 0.7357
Epoch 46/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5435 - accuracy: 0.7361
Epoch 47/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5439 - accuracy: 0.7346
Epoch 48/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5437 - accuracy: 0.7360
Epoch 49/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5445 - accuracy: 0.7357
Epoch 50/200
804/804 [==============================] - 2s 3ms/step - loss: 0.5436 - accuracy: 0.7355
Epoch 51/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5436 - accuracy: 0.7348
Epoch 52/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5434 - accuracy: 0.7355
Epoch 53/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5436 - accuracy: 0.7361
Epoch 54/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5427 - accuracy: 0.7350
Epoch 55/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5436 - accuracy: 0.7353
Epoch 56/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5428 - accuracy: 0.7356
Epoch 57/200
804/804 [==============================] - 2s 3ms/step - loss: 0.5431 - accuracy: 0.7355
Epoch 58/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5431 - accuracy: 0.7355
Epoch 59/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5427 - accuracy: 0.7352
Epoch 60/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5434 - accuracy: 0.7355
Epoch 61/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5427 - accuracy: 0.7357
Epoch 62/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5421 - accuracy: 0.7365
Epoch 63/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5425 - accuracy: 0.7353
Epoch 64/200
804/804 [==============================] - 2s 3ms/step - loss: 0.5431 - accuracy: 0.7360
Epoch 65/200
804/804 [==============================] - 2s 3ms/step - loss: 0.5425 - accuracy: 0.7355
Epoch 66/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5425 - accuracy: 0.7363
Epoch 67/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5428 - accuracy: 0.7355
Epoch 68/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5422 - accuracy: 0.7357
Epoch 69/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5428 - accuracy: 0.7356
Epoch 70/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5420 - accuracy: 0.7360
Epoch 71/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5422 - accuracy: 0.7355
Epoch 72/200
804/804 [==============================] - 2s 3ms/step - loss: 0.5426 - accuracy: 0.7362
Epoch 73/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5422 - accuracy: 0.7362
Epoch 74/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5420 - accuracy: 0.7360
Epoch 75/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5418 - accuracy: 0.7359
Epoch 76/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5423 - accuracy: 0.7362
Epoch 77/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5423 - accuracy: 0.7356
Epoch 78/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5420 - accuracy: 0.7360
Epoch 79/200
804/804 [==============================] - 3s 3ms/step - loss: 0.5418 - accuracy: 0.7363
Epoch 80/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5417 - accuracy: 0.7364
Epoch 81/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5416 - accuracy: 0.7362
Epoch 82/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5420 - accuracy: 0.7358
Epoch 83/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5415 - accuracy: 0.7365
Epoch 84/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5418 - accuracy: 0.7355
Epoch 85/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5415 - accuracy: 0.7361
Epoch 86/200
804/804 [==============================] - 2s 3ms/step - loss: 0.5417 - accuracy: 0.7363
Epoch 87/200
804/804 [==============================] - 2s 3ms/step - loss: 0.5420 - accuracy: 0.7364
Epoch 88/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5420 - accuracy: 0.7357
Epoch 89/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5411 - accuracy: 0.7364
Epoch 90/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5411 - accuracy: 0.7360
Epoch 91/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5414 - accuracy: 0.7356
Epoch 92/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5413 - accuracy: 0.7359
Epoch 93/200
804/804 [==============================] - 2s 3ms/step - loss: 0.5418 - accuracy: 0.7351
Epoch 94/200
804/804 [==============================] - 2s 3ms/step - loss: 0.5409 - accuracy: 0.7359
Epoch 95/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5425 - accuracy: 0.7365
Epoch 96/200
804/804 [==============================] - 2s 3ms/step - loss: 0.5432 - accuracy: 0.7365
Epoch 97/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5415 - accuracy: 0.7360
Epoch 98/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5408 - accuracy: 0.7366
Epoch 99/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5409 - accuracy: 0.7369
Epoch 100/200
804/804 [==============================] - 2s 3ms/step - loss: 0.5411 - accuracy: 0.7360
Epoch 101/200
804/804 [==============================] - 2s 3ms/step - loss: 0.5409 - accuracy: 0.7363
Epoch 102/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5414 - accuracy: 0.7361
Epoch 103/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5409 - accuracy: 0.7361
Epoch 104/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5413 - accuracy: 0.7360
Epoch 105/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5408 - accuracy: 0.7361
Epoch 106/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5411 - accuracy: 0.7362
Epoch 107/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5406 - accuracy: 0.7366
Epoch 108/200
804/804 [==============================] - 2s 3ms/step - loss: 0.5410 - accuracy: 0.7364
Epoch 109/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5417 - accuracy: 0.7363
Epoch 110/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5416 - accuracy: 0.7367
Epoch 111/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5420 - accuracy: 0.7366
Epoch 112/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5412 - accuracy: 0.7363
Epoch 113/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5411 - accuracy: 0.7360
Epoch 114/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5405 - accuracy: 0.7365
Epoch 115/200
804/804 [==============================] - 2s 3ms/step - loss: 0.5408 - accuracy: 0.7352
Epoch 116/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5408 - accuracy: 0.7367
Epoch 117/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5409 - accuracy: 0.7360
Epoch 118/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5405 - accuracy: 0.7366
Epoch 119/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5404 - accuracy: 0.7362
Epoch 120/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5418 - accuracy: 0.7359
Epoch 121/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5405 - accuracy: 0.7363
Epoch 122/200
804/804 [==============================] - 2s 3ms/step - loss: 0.5420 - accuracy: 0.7364
Epoch 123/200
804/804 [==============================] - 2s 3ms/step - loss: 0.5405 - accuracy: 0.7362
Epoch 124/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5405 - accuracy: 0.7367
Epoch 125/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5404 - accuracy: 0.7360
Epoch 126/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5403 - accuracy: 0.7357
Epoch 127/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5402 - accuracy: 0.7357
Epoch 128/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5420 - accuracy: 0.7358
Epoch 129/200
804/804 [==============================] - 2s 3ms/step - loss: 0.5403 - accuracy: 0.7358
Epoch 130/200
804/804 [==============================] - 2s 3ms/step - loss: 0.5404 - accuracy: 0.7365
Epoch 131/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5407 - accuracy: 0.7365
Epoch 132/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5403 - accuracy: 0.7364
Epoch 133/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5415 - accuracy: 0.7360
Epoch 134/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5411 - accuracy: 0.7363
Epoch 135/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5412 - accuracy: 0.7362
Epoch 136/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5405 - accuracy: 0.7366
Epoch 137/200
804/804 [==============================] - 2s 3ms/step - loss: 0.5401 - accuracy: 0.7365
Epoch 138/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5405 - accuracy: 0.7362
Epoch 139/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5415 - accuracy: 0.7363
Epoch 140/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5404 - accuracy: 0.7362
Epoch 141/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5401 - accuracy: 0.7354
Epoch 142/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5407 - accuracy: 0.7358
Epoch 143/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5415 - accuracy: 0.7362
Epoch 144/200
804/804 [==============================] - 3s 3ms/step - loss: 0.5400 - accuracy: 0.7365
Epoch 145/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5418 - accuracy: 0.7359
Epoch 146/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5411 - accuracy: 0.7365
Epoch 147/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5402 - accuracy: 0.7359
Epoch 148/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5403 - accuracy: 0.7366
Epoch 149/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5407 - accuracy: 0.7360
Epoch 150/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5403 - accuracy: 0.7369
Epoch 151/200
804/804 [==============================] - 2s 3ms/step - loss: 0.5406 - accuracy: 0.7367
Epoch 152/200
804/804 [==============================] - 2s 3ms/step - loss: 0.5401 - accuracy: 0.7365
Epoch 153/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5401 - accuracy: 0.7362
Epoch 154/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5416 - accuracy: 0.7354
Epoch 155/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5404 - accuracy: 0.7364
Epoch 156/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5404 - accuracy: 0.7366
Epoch 157/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5400 - accuracy: 0.7363
Epoch 158/200
804/804 [==============================] - 2s 3ms/step - loss: 0.5403 - accuracy: 0.7363
Epoch 159/200
804/804 [==============================] - 2s 3ms/step - loss: 0.5398 - accuracy: 0.7363
Epoch 160/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5413 - accuracy: 0.7365
Epoch 161/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5406 - accuracy: 0.7370
Epoch 162/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5399 - accuracy: 0.7362
Epoch 163/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5412 - accuracy: 0.7369
Epoch 164/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5438 - accuracy: 0.7372
Epoch 165/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5397 - accuracy: 0.7369
Epoch 166/200
804/804 [==============================] - 3s 3ms/step - loss: 0.5398 - accuracy: 0.7372
Epoch 167/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5398 - accuracy: 0.7362
Epoch 168/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5397 - accuracy: 0.7366
Epoch 169/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5400 - accuracy: 0.7366
Epoch 170/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5401 - accuracy: 0.7367
Epoch 171/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5400 - accuracy: 0.7365
Epoch 172/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5397 - accuracy: 0.7362
Epoch 173/200
804/804 [==============================] - 2s 3ms/step - loss: 0.5397 - accuracy: 0.7369
Epoch 174/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5402 - accuracy: 0.7365
Epoch 175/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5397 - accuracy: 0.7365
Epoch 176/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5401 - accuracy: 0.7359
Epoch 177/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5398 - accuracy: 0.7363
Epoch 178/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5400 - accuracy: 0.7367
Epoch 179/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5398 - accuracy: 0.7370
Epoch 180/200
804/804 [==============================] - 2s 3ms/step - loss: 0.5398 - accuracy: 0.7365
Epoch 181/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5398 - accuracy: 0.7364
Epoch 182/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5400 - accuracy: 0.7360
Epoch 183/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5435 - accuracy: 0.7364
Epoch 184/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5400 - accuracy: 0.7365
Epoch 185/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5397 - accuracy: 0.7369
Epoch 186/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5412 - accuracy: 0.7359
Epoch 187/200
804/804 [==============================] - 2s 3ms/step - loss: 0.5403 - accuracy: 0.7364
Epoch 188/200
804/804 [==============================] - 2s 3ms/step - loss: 0.5395 - accuracy: 0.7367
Epoch 189/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5393 - accuracy: 0.7365
Epoch 190/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5398 - accuracy: 0.7363
Epoch 191/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5397 - accuracy: 0.7367
Epoch 192/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5402 - accuracy: 0.7367
Epoch 193/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5426 - accuracy: 0.7361
Epoch 194/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5397 - accuracy: 0.7369
Epoch 195/200
804/804 [==============================] - 2s 3ms/step - loss: 0.5396 - accuracy: 0.7366
Epoch 196/200

In [27]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5704 - accuracy: 0.7272 - 652ms/epoch - 2ms/step
Loss: 0.5703943967819214, Accuracy: 0.7272303104400635